### ISSUE TITLE
X-MoneyTrace or Money

### ISSUE THREAD

**Issue by gtrevg** [Comcast/golang-money#8]
I noticed in the [documentation](https://github.com/Comcast/golang-money#start-server-and-make-a-request-that-includes-a-money-header) of this project it says the header should be:

```
Money: trace-id=YourTraceId;parent-id=12345;span-id=12346;span-name=YourSpanName;start-time=2016-02-15T20:30:46.782538292Z;span-duration=3000083865;error-code=200;span-success=true
```

But in the [documentation](https://github.com/Comcast/money/wiki#how-do-we-make-distributed-tracing-work) of the project that this implements, it says the header should be:

```
X-MoneyTrace: trace-id=de305d54-75b4-431b-adb2-eb6b9e546013;parent-id=3285573610483682037;span-id=3285573610483682037
```

What header should it be?  `X-MoneyTrace` or `Money` ?

Thanks

**Comment by njharter** [comment]
Currently, the header used is `Money`.  This is wrong.  It should match the project documentation and use `X-MoneyTrace`.  Thanks.

**Comment by gtrevg** [comment]
Excellent.  Thanks for the clarification.

**Comment by joe94** [comment]
Closing due to age. New implementation will use `X-MoneyTrace`.
